name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-gate:
    name: Build Gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v17
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build dev shell
        run: nix build --quiet .#devShells.x86_64-linux.default.inputDerivation

  build:
    name: CI build
    needs: build-gate
    runs-on: nixos
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v17
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix develop --quiet -c just ci

